[project]
name = "cdda-game-launcher"
version = "1.8.9"
description = "A Cataclysm: Dark Days Ahead launcher with additional features"
requires-python = ">=3.9"
dependencies = [
    "cssselect>=1.3.0",
    "html5lib>=1.1",
    "pyinstaller>=6.17.0",
]
